### ISSUE TITLE
你好 我的鼠标明明没有按 为什么一直在锁定呢

### ISSUE THREAD

**Issue by lrlye** [EthanH3514/AL_Yolo#13]
我尝试百度搜了一下apex的图片 然后我的鼠标就开始锁定了明明我什么按键都没有按 请问 是通过什么按键锁定的呢

**Comment by lrlye** [comment]
[这是这个问题的视频 请过目一下
[https://pan.baidu.com/s/1lzZ9ZISLvW_clxrVuZK0Sw?pwd=3cr4](url)

**Comment by lrlye** [comment]
这是我修改的代码设置 
![image](https://github.com/EthanH3514/AL_Yolo/assets/93723706/39014a45-d563-4b1c-8dda-3a201aae95cf)

**Comment by EthanH3514** [comment]
因为目前还没有写锁定开关的逻辑，就是启动程序之后就一直在锁定了。如果只是想检验目标检测的效果的话可以把鼠标移动逻辑关掉再运行程序，具体操作如下：

将 `apex.py` 中的 `release` 函数内关于鼠标锁定的函数注释掉：

```python
def release(key):
    if key == pynput.keyboard.Key.home:  # Home
        winsound.Beep(400, 200)
        # mouse_control.run()
        return False
    elif key == pynput.keyboard.Key.end:  # End
        winsound.Beep(600, 200)
        # mouse_control.stop()
        return False

```

然后保存，重新运行

**Comment by lrlye** [comment]
> 因为目前还没有写锁定开关的逻辑，就是启动程序之后就一直在锁定了。如果只是想检验目标检测的效果的话可以把鼠标移动逻辑关掉再运行程序，具体操作如下：
> 
> 将 中的 函数内关于鼠标锁定的函数注释掉：`apex.py``release`
> 
> ```python
> def release(key):
>     if key == pynput.keyboard.Key.home:  # Home
>         winsound.Beep(400, 200)
>         # mouse_control.run()
>         return False
>     elif key == pynput.keyboard.Key.end:  # End
>         winsound.Beep(600, 200)
>         # mouse_control.stop()
>         return False
> ```
> 
> 然后保存，重新运行

好的 谢谢 我后面也想到了
