### ISSUE TITLE
dxshot怎么导入？好像识别不了

### ISSUE THREAD

**Issue by dclemon** [EthanH3514/AL_Yolo#15]
import dxshot.pyd
ImportError: DLL load failed while importing dxshot: 找不到指定的模块。

**Comment by EthanH3514** [comment]
[issue](https://github.com/EthanH3514/AL_Yolo/issues/8#issuecomment-1646494066)

看一下这个能不能解决？

**Comment by dclemon** [comment]
> [issue](https://github.com/EthanH3514/AL_Yolo/issues/8#issuecomment-1646494066)
> 
> 看一下这个能不能解决？

还是同样的报错，python是3.11

**Comment by EthanH3514** [comment]
换成python3.10试试，python3.11似乎有一些兼容性问题

**Comment by dclemon** [comment]
有没有交流群？有些改进建议

**Comment by EthanH3514** [comment]
> 有没有交流群？有些改进建议

没交流群，有改进建议可以提在issue里或者提交pr

最近不会有太多精力在这个项目上，所以应该也不会搞交流群

**Comment by EthanH3514** [comment]
Duplicate of #8

**Comment by suyu926** [comment]
import dxshot
ImportError: DLL load failed while importing dxshot: 找不到指定的模块。

**Comment by EthanH3514** [comment]
> ```
> import dxshot
> ```
> 
> ImportError: DLL load failed while importing dxshot: 找不到指定的模块。

有没有目录结构以及环境等信息，我无法复现这个问题

**Comment by dclemon** [comment]
我3.11试了好久放弃了，另起炉灶搞了个win32截图的版本。。。另外其实这个项目完全没必要用罗技驱动，普通的pynput.mouse在游戏中也可以控制鼠标，而且安全性不需要担心，我自己写的脚本用了一年没问题

**Comment by suyu926** [comment]
> 我3.11试了好久放弃了，另起炉灶搞了个win32截图的版本。。。另外其实这个项目完全没必要用罗技驱动，普通的pynput.mouse在游戏中也可以控制鼠标，而且安全性不需要担心，我自己写的脚本用了一年没问题

win32的版本可以开源吗？

**Comment by dclemon** [comment]
> > 我3.11试了好久放弃了，另起炉灶搞了个win32截图的版本。。。另外其实这个项目完全没必要用罗技驱动，普通的pynput.mouse在游戏中也可以控制鼠标，而且安全性不需要担心，我自己写的脚本用了一年没问题
> 
> win32的版本可以开源吗？

看一下这个https://github.com/dclemon/APEX_YOLOV5_aimbot

**Comment by dclemon** [comment]
> > 我3.11试了好久放弃了，另起炉灶搞了个win32截图的版本。。。另外其实这个项目完全没必要用罗技驱动，普通的pynput.mouse在游戏中也可以控制鼠标，而且安全性不需要担心，我自己写的脚本用了一年没问题
> 
> 这个项目是3.10的，在项目刚开始写的时候好像有个库是不适配3.11的，不知道现在有没有问题。
> 
> pynput.mouse 我记得我测过效率不高，罗技驱动的cps有4w+，效率很高
这个你可以参考一下，把绘制方框加进去
https://github.com/dclemon/APEX_YOLOV5_aimbot

**Comment by EthanH3514** [comment]
> > > 我3.11试了好久放弃了，另起炉灶搞了个win32截图的版本。。。另外其实这个项目完全没必要用罗技驱动，普通的pynput.mouse在游戏中也可以控制鼠标，而且安全性不需要担心，我自己写的脚本用了一年没问题
> > 
> > 
> > 这个项目是3.10的，在项目刚开始写的时候好像有个库是不适配3.11的，不知道现在有没有问题。
> > pynput.mouse 我记得我测过效率不高，罗技驱动的cps有4w+，效率很高
> > 这个你可以参考一下，把绘制方框加进去
> > https://github.com/dclemon/APEX_YOLOV5_aimbot

我的项目之前是有可视化的，但是因为 cv2.imshow 的效率比较低于是去掉了，在正常游玩过程中可视化的作用可有可无，所以就去掉了
