### ISSUE TITLE
1

### ISSUE THREAD

**Issue by 525957887** [EthanH3514/AL_Yolo#16]
![()H8WBQSN{@`0RM_R BGVNF](https://github.com/EthanH3514/AL_Yolo/assets/136997577/a9f415c8-1c1f-43d8-8f51-0ffe34dc0e75)
![image](https://github.com/EthanH3514/AL_Yolo/assets/136997577/d54b2eb6-d87d-46c2-8f93-b7ebab50eb71)
检测不到鼠标怎么办，我也用管理员运行了

**Comment by EthanH3514** [comment]
这个不是因为检测不到鼠标，而是因为缺少对应的python库

在python环境下输入 `pip install pyautogui` 即可完成安装

**Comment by 525957887** [comment]
已经弄好了嘿嘿，谢谢



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 9, 2023 18:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [EthanH3514/AL_Yolo] 1 (Issue #16)




 
这个不是因为检测不到鼠标，而是因为缺少对应的python库
 
在python环境下输入 pip install pyautogui 即可完成安装
