### ISSUE TITLE
高刷屏还是卡在六十多帧

### ISSUE THREAD

**Issue by loadingfd** [EthanH3514/AL_Yolo#20]
用dxshot库那个演示能四百多帧数

**Comment by EthanH3514** [comment]
我在测试的时候也出现过这个问题，我屏幕刷新率是144Hz，但是测试的过程中也是卡在了60多帧。

后来我去测试了一下dxshot，dxshot在我的本地跑最多也就不到100帧，感觉dxshot的上限并没有那么容易达到

当然也有我的代码优化有点差的原因

**Comment by loadingfd** [comment]
应该是cv的问题吧

**Comment by loadingfd** [comment]
不对，要是截图帧率就高，videomode就六十多帧

**Comment by EthanH3514** [comment]
> 不对，要是截图帧率就高，videomode就六十多帧

截图的帧率不是很稳定，去掉所有空帧的话和videomode帧率差不多
