### ISSUE TITLE
求数据集使用教程

### ISSUE THREAD

**Issue by coderYxl** [EthanH3514/AL_Yolo#22]
求数据集的树状目录以及内容

**Comment by EthanH3514** [comment]
数据集在 `./exp` 路径下，具体怎么用我只在这个项目用过，也没做过迁移，你可以摸索摸索

**Comment by EthanH3514** [comment]
> 求数据集的树状目录以及内容

翻issue的时候发现了这个issue，非常抱歉当时看错了你的问题，把数据集看成模型了😥

数据集来源是 [AL-YOLO-dataset](https://github.com/goldjee/AL-YOLO-dataset) ，下面有上万个图片，每个图片对应一个相同名称的txt文件，这个txt文件里面写着识别目标的类别以及框的坐标

我当时是把其中全屏截图的数据删掉了，剩下的都是屏幕中心一小部分的图片。把这些数据按一定比例分成训练集和测试集(具体的比例忘掉了，数据集也没有本地保存)，然后列成yolo要求的目录结构进行训练的

**Comment by ParticleG** [comment]
> > 求数据集的树状目录以及内容
> 
> 翻issue的时候发现了这个issue，非常抱歉当时看错了你的问题，把数据集看成模型了😥
> 
> 数据集来源是 [AL-YOLO-dataset](https://github.com/goldjee/AL-YOLO-dataset) ，下面有上万个图片，每个图片对应一个相同名称的txt文件，这个txt文件里面写着识别目标的类别以及框的坐标
> 
> 我当时是把其中全屏截图的数据删掉了，剩下的都是屏幕中心一小部分的图片。把这些数据按一定比例分成训练集和测试集(具体的比例忘掉了，数据集也没有本地保存)，然后列成yolo要求的目录结构进行训练的

Yolo v8 需要的目录结构不太一样，请问这一堆里面哪些算训练数据集(Train)，哪些算验证数据集(Val)，哪些算测试数据集(Test)
