### ISSUE TITLE
全国首例“AI外挂”案侦办记

### ISSUE THREAD

**Issue by children520** [EthanH3514/AL_Yolo#23]

**Comment by EthanH3514** [comment]
你想表达什么

**Comment by EthanH3514** [comment]
希望看到这个issue的其他人之后提issue的时候不要像这个一样，起一个莫名其妙的标题，没有任何描述，被提问之后光速close掉，啥也不说

这样的issue没有任何有效沟通，并且对他人很不尊重

**Comment by children520** [comment]
实在不好意思，以后注意


肖骏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EthanH3514/AL_Yolo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月27日(星期一) 晚上9:24
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [EthanH3514/AL_Yolo] 全国首例“AI外挂”案侦办记 (Issue #23)





 
希望看到这个issue的其他人之后提issue的时候不要像这个一样，起一个莫名其妙的标题，没有任何描述，被提问之后光速close掉，啥也不说
 
这样的issue没有任何有效沟通，并且对他人很不尊重
