### ISSUE TITLE
依赖文件都指向本地目录。

### ISSUE THREAD

**Issue by houziyu** [EthanH3514/AL_Yolo#24]
requirements.txt中依赖都指向本地目录。

**Comment by houziyu** [comment]
还是用第一次commit的就可以？

**Comment by houziyu** [comment]
CUDA 11 如果是A卡怎么办？是不是无法使用了？

**Comment by EthanH3514** [comment]
> CUDA 11 如果是A卡怎么办？是不是无法使用了？

应该是不支持A卡了，这个项目并没有做兼容性的优化

**Comment by EthanH3514** [comment]
> requirements.txt中依赖都指向本地目录。

这个没看懂，指向本地目录是什么意思？

**Comment by EthanH3514** [comment]
> 还是用第一次commit的就可以？

第一次commit的那个是Yolov5的依赖，安装了之后还是会有一些额外的依赖需要安装，建议使用最新的requirements

**Comment by houziyu** [comment]
![WX20231129-101152](https://github.com/EthanH3514/AL_Yolo/assets/17023204/0ebc1cc0-3920-46e2-b224-8a8906c4c9ee)
pip list --format=freeze > requirements.txt

**Comment by EthanH3514** [comment]
感谢你的issue，应该已经修复了
