### ISSUE TITLE
罗技驱动失效

### ISSUE THREAD

**Issue by hongjijun233** [EthanH3514/AL_Yolo#26]
请问一下作者用的是什么版本的GHUB，我尝试了几个旧版本的GHUB都无法使用这个dll
（无法使用即调用.mouse_open()返回为0）

另外请问：我在git上尝试想要搜索这个dll的来源，似乎没有找到有，是我的搜索姿势不对吗，也想顺便请教这个驱动的来源是哪里，谢谢！

**Comment by EthanH3514** [comment]
版本是 21.3

驱动的来源是一个参考的项目：[APEX_AIMBOT](https://github.com/NTUYWANG103/APEX_AIMBOT/tree/master/mouse_driver)

**Comment by hongjijun233** [comment]
感谢回复，换了几个版本的驱动似乎能用了
