### ISSUE TITLE
requirements问题

### ISSUE THREAD

**Issue by GreshAnt** [EthanH3514/AL_Yolo#27]
兄弟你确定你用到了这么多库吗，你是不是把你的整个电脑里面的库都打包给我了，可以搞虚拟环境来解决这个问题，我安装这些库都快死了，死活安不上

**Comment by EthanH3514** [comment]
其实这个也是用了虚拟环境的(0.0)

用不到这么多库，最开始搞这个项目的时候是把 [yolov5](https://github.com/ultralytics/ultralytics) 拉过来改写的，依赖一开始也是用的 yolov5 的依赖的requirements.txt，后来逐步改写，没用到的依赖也没有去删除，所以后来的依赖越来越多

我现在重新开了一个虚拟环境重新配了一遍依赖，已经更新到 `requirements.txt` 中了，虽然可能还是有很多库用不到，但是在不改代码的情况下能做到最简了
