### ISSUE TITLE
请问 打开python apex.py之后具体应该怎么操作

### ISSUE THREAD

**Issue by flask30k** [EthanH3514/AL_Yolo#30]
你好 我是一个一窍不通的小白，摸索了大概三个小时用powershell打开了apex.py，后面的内容我太了解具体该怎么做

要把https://github.com/ultralytics/yolov5和https://github.com/goldjee/AL-YOLO-dataset的内容下载下来吗？

已点star

烦请指点一二，或者告诉请我应该学习哪方面的内容，非常感谢

**Comment by EthanH3514** [comment]
不用下载数据集，数据集是用来训练模型的

可以学一下并配置anaconda并创建虚拟环境，学一下pip知道pip的一些基础命令，然后去配置cuda、cudnn、pytorch，接着就是把这个项目下载下来，在项目文件夹下面以管理员模式打开终端，激活之前创建的虚拟环境， `pip install -r requirements.txt` ，然后没有问题的话就可以 `python apex.py` 启动了，启动之后有个图形化界面，后面应该很友好的

**Comment by flask30k** [comment]
谢谢你的回复 我已经启动了这个
![1](https://github.com/EthanH3514/AL_Yolo/assets/34526337/ad2aecec-a375-465f-bfbf-52307d29cdb1)

剩下的 只需要点开始目标检测就好了吧

**Comment by flask30k** [comment]
非常感谢 已有效果 折腾这个的过程甚至比游戏还要好玩
