### ISSUE TITLE
使用DAMO-YOLO替代YOLOv5并优化检测开关

### ISSUE THREAD

**Issue by Chikage0o0** [EthanH3514/AL_Yolo#4]
实际上屏幕检测并不需要检测多种物体，仅仅是检测Person以及Head，似乎使用[DAMO-YOLO](https://github.com/tinyvision/damo-yolo)能使程序占用更小一部分硬件资源，使用LightModel检测416x416像素区域已经可以满足开镜状态下跟枪的需求。对于APEX长TTK的游戏来说，稳定的跟枪比拉枪更重要。

同时在腰射状态下的识别与瞄准也没有必要，这时人物移动幅度过大，超出640的检测区域，这时候开启鼠标移动会因为错误的识别而导致人物鬼畜。

建议仅仅在右键开镜状态下，开启程序相关功能。

**Comment by Buags** [comment]
老哥，我能问个事？CUDA 11这个环境是N卡的应用，我的amd的显卡是不是用不了这个AI程序

**Comment by EthanH3514** [comment]
> 老哥，我能问个事？CUDA 11这个环境是N卡的应用，我的amd的显卡是不是用不了这个AI程序

是的，AMD显卡不支持cuda

（还有这个问题其实应该新建一个issue，因为和这个issue内的问题并不相关

**Comment by Chikage0o0** [comment]
> 老哥，我能问个事？CUDA 11这个环境是N卡的应用，我的amd的显卡是不是用不了这个AI程序

是的，单纯使用可以考虑ncnn进行推理

**Comment by Chikage0o0** [comment]
@EthanH3514 最近看了下https://github.com/EthanH3514/AL_Yolo/blob/master/mouse_control.py，目标的选择在有多个目标时候貌似无法正常处理。

**Comment by EthanH3514** [comment]
> @EthanH3514 最近看了下 https://github.com/EthanH3514/AL_Yolo/blob/master/mouse_control.py ，目标的选择在有多个目标时候貌似无法正常处理。

多目标我测试过，靠左靠上的目标优先级更高，这是由检测函数决定的，之后会改为靠中间的优先级更高

**Comment by Chikage0o0** [comment]
自己测试了一下DAMO的体验并不是太好

**Comment by EthanH3514** [comment]
> > @EthanH3514 最近看了下 https://github.com/EthanH3514/AL_Yolo/blob/master/mouse_control.py ，目标的选择在有多个目标时候貌似无法正常处理。
> 
> 多目标我测试过，靠左靠上的目标优先级更高，这是由检测函数决定的，之后会改为靠中间的优先级更高

已经修改为越靠近中心的优先级越高
