### ISSUE TITLE
无法正常启动？

### ISSUE THREAD

**Issue by fatinghenji** [EthanH3514/AL_Yolo#6]
```python
(base) PS G:\AI\AL_Yolo> conda activate AL_Yolo
(AL_Yolo) PS G:\AI\AL_Yolo> python apex.py
[1280.0, 720.0] (2560, 1440)
```
罗技驱动版本：
![image](https://github.com/EthanH3514/AL_Yolo/assets/37131177/85493965-2e40-4bca-8481-c863c028fc4b)
python版本：3.10
除使用`pip install -r requirements.txt`进行pypi包安装外，另按照报错手动安装了`pynput`、`comtypes`、 `pyautogui`请问是哪里配置出错了吗？

**Comment by EthanH3514** [comment]
运行脚本之后等待提示声音出现说明初始化完成，此时再按下 `home` 键启动程序，按这个流程试一试？

如果还是有问题，请提供更详细的报错信息或者截图

**Comment by fatinghenji** [comment]
```
(AL_Yolo) PS G:\AI\AL_Yolo> python apex.py
[1280.0, 720.0] (2560, 1440)
Traceback (most recent call last):
  File "G:\AI\AL_Yolo\apex.py", line 34, in <module>
    detector.work()
  File "G:\AI\AL_Yolo\detect.py", line 168, in work
    self.run(self)
  File "G:\AI\AL_Yolo\detect.py", line 58, in run
    device = select_device('0')
  File "G:\AI\AL_Yolo\utils\torch_utils.py", line 118, in select_device
    assert torch.cuda.is_available() and torch.cuda.device_count() >= len(device.replace(',', '')), \
AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)
```
感觉是cuda的问题
```
thop               0.1.1.post2209072238
torch              2.0.1
torchvision        0.15.2
```
但是pip list里面是安装的有torch的

**Comment by EthanH3514** [comment]
- 是否配置过CUDA？如果配置过，试试检查版本之间是否匹配
- 可以打开 `任务管理器-设备` 看看你的GPU的编号是否有为0的，如果没有，将 `AL_Yolo\detect.py` 中 `device = select_device('0')` 的 `0` 改为可用的GPU编号
- 保底的解决方法是使用CPU处理图像（这会很慢），方法是将 `AL_Yolo\detect.py` 中 `device = select_device('0')` 的 `0` 改为 `cpu`

**Comment by fatinghenji** [comment]
> * 是否配置过CUDA？如果配置过，试试检查版本之间是否匹配
> * 可以打开 `任务管理器-设备` 看看你的GPU的编号是否有为0的，如果没有，将 `AL_Yolo\detect.py` 中 `device = select_device('0')` 的 `0` 改为可用的GPU编号
> * 保底的解决方法是使用CPU处理图像（这会很慢），方法是将 `AL_Yolo\detect.py` 中 `device = select_device('0')` 的 `0` 改为 `cpu`

可能是版本不匹配。本项目指定的 cuda 版本有要求吗？

**Comment by EthanH3514** [comment]
本项目没有指定cuda版本

只需要cuda、cudnn和torch版本匹配并且不超过自己gpu最高支持版本就行

**Comment by SakuraVAC** [comment]
我是cuda12.1 也是报错 没有找到cuda

**Comment by blraksd** [comment]
我cuda版本12.1，py版本3.10，下载该版本pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118成功解决了

**Comment by EthanH3514** [comment]
> ```
> (AL_Yolo) PS G:\AI\AL_Yolo> python apex.py
> [1280.0, 720.0] (2560, 1440)
> Traceback (most recent call last):
>   File "G:\AI\AL_Yolo\apex.py", line 34, in <module>
>     detector.work()
>   File "G:\AI\AL_Yolo\detect.py", line 168, in work
>     self.run(self)
>   File "G:\AI\AL_Yolo\detect.py", line 58, in run
>     device = select_device('0')
>   File "G:\AI\AL_Yolo\utils\torch_utils.py", line 118, in select_device
>     assert torch.cuda.is_available() and torch.cuda.device_count() >= len(device.replace(',', '')), \
> AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)
> ```
> 
> 感觉是cuda的问题
> 
> ```
> thop               0.1.1.post2209072238
> torch              2.0.1
> torchvision        0.15.2
> ```
> 
> 但是pip list里面是安装的有torch的

可能是因为配置的torch是cpu版本的，可以用python测一下环境中的torch，代码如下
```python
import torch
print(torch.__version__)
print(torch.cuda.is_available())
```
如果torch是cpu版本的那么是不支持gpu加速的，可以去[这里](https://pytorch.org/get-started/previous-versions/)查找自己机器可以支持的pytorch，使用官网上的命令行安装

**Comment by EthanH3514** [comment]
我复现了这个issue的问题，按上述方法解决的，如果还没有解决可以重新open这个issue
