### ISSUE TITLE
启动失败：DLL load failed while importing dxshot: 找不到指定的模块。

### ISSUE THREAD

**Issue by Jackle910** [EthanH3514/AL_Yolo#8]
Traceback (most recent call last):
  File "E:\codespace\AL_Yolo\apex.py", line 2, in <module>
    from detect import YOLOv5Detector
  File "E:\codespace\AL_Yolo\detect.py", line 11, in <module>
    from Capture import LoadScreen
  File "E:\codespace\AL_Yolo\Capture.py", line 1, in <module>
    import dxshot
ImportError: DLL load failed while importing dxshot: 找不到指定的模块。
dxshot模块在哪呢？

**Comment by EthanH3514** [comment]
dxshot在 `AL_Yolo\dxshot.pyd` 中，请检查 `dxshot.pyd` 是否在工作目录下

如果 `dxshot.pyd` 在工作目录下仍然报错，请尝试将 `Capturer.py` 中前面的import部分改写成下面这样：
```py
import pyautogui
from utils.augmentations import letterbox
import numpy as np
import time
import sys
import os

ROOT = os.getcwd()
sys.path.append(os.path.join(ROOT, "dxshot.pyd"))

import dxshot
````

**Comment by loadingfd** [comment]
还有注意python版本

**Comment by Junjun7** [comment]
然而并不行，所以哥，你的pyd里面有dxshot吗，要不开源下嘛

**Comment by EthanH3514** [comment]
> 然而并不行，所以哥，你的pyd里面有dxshot吗，要不开源下嘛

`dxshot` 就是 `./dxshot.pyd` ，在主目录下
